name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/qelphybox/fuckdo/fuckdo:latest
    - run: docker login docker.pkg.github.com -u qelphybox -p $(GITHUB_TOKEN)
    - run: docker push docker.pkg.github.com/qelphybox/fuckdo/fuckdo:latest
      
      
